<?php

function form_project_menu() {

  $items = array();
  $items['project/form_project'] = array(
    'title' => 'Swapps Projects',
    'page callback' => 'form_project_info',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );
  $items['project/form_project/create'] = array(
    'title' => 'Create Project',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_create_project'),
    'access callback' => TRUE,
    'description' => '',
    'type' => MENU_NORMAL_ITEM,
    //'file' => 'form_create_project.inc',
  );
  return $items;
}

/**
 * Page callback for our general info page.
 */

function form_project_info() {
  $markup = t('Create Swapps projects');
  return array('#markup' => $markup);
}

/**
 * Create Project form.
Project
Image

CLIENT
Name
Country (Taxonomy)

*/


function form_create_project($form, &$form_state) {
  
 $form['project'] = array(
    '#type' => 'textfield',
    '#title' => 'Project Name',
    '#size' => 50,
    '#maxlength' => 50,
    '#required' => TRUE,
  );
  $form['url'] = array(
    '#type' => 'textfield',
    '#title' => 'URL Project',
    '#size' => 100,
    '#maxlength' => 100,
    '#required' => TRUE,
  );
  $form['client'] = array(
    '#type' => 'textfield',
    '#title' => 'Client',
    '#size' => 50,
    '#maxlength' => 50,
    '#required' => TRUE,
  );
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  
  return $form;
}
